import { Nav } from "@/components/nav/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="m-2 relative">
          <Nav/>
          <main  className="relative">{children}</main>
        </div>
      </body>
    </html>
  );
}
